[build]
command = "npm install && nuxt build"
directory = ".output/public"

[build.environment]
NODE_VERSION = "20"
NPM_FLAGS = "--prefer-offline --no-audit"

[site]
bucket = ".output/public"

[env.production]
routes = [
  { pattern = "/_nuxt/*", asset = true },
  { pattern = "/images/*", asset = true },
  { pattern = "/favicon.ico", asset = true },
  { pattern = "/*", function = "functions", asset = false }
]

[functions]
directory = ".output/server" 