[build]
command = "NODE_OPTIONS=\"--max-old-space-size=4096 --no-experimental-fetch\" npm install --omit=optional --no-package-lock && npm run build"
directory = ".output/public"

[build.environment]
NODE_VERSION = "20"
NPM_FLAGS = "--prefer-offline --no-audit --no-package-lock --omit=optional"
ROLLUP_SKIP_BROWSER_BUILD = "true"
NODE_ENV = "production"

[site]
bucket = ".output/public"

[env.production]
routes = [
  { pattern = "/_nuxt/*", asset = true },
  { pattern = "/images/*", asset = true },
  { pattern = "/favicon.ico", asset = true },
  { pattern = "/*", function = "functions", asset = false }
]

[functions]
directory = ".output/server" 